export const SKILLS_TAXONOMY: Record<string, string[]> = {
  languages: [
    "typescript",
    "javascript",
    "python",
    "java",
    "c++",
    "c#",
    "html",
    "css",
    "go",
    "rust",
    "ruby",
    "swift",
    "kotlin",
    "php",
    "sass",
    "scala",
    "elixir",
    "haskell",
    "r",
  ],
  frontend: [
    "react",
    "next.js",
    "nextjs",
    "vue",
    "nuxt",
    "angular",
    "svelte",
    "tailwind",
    "design systems",
    "accessibility",
    "web performance",
  ],
  "backend/data": [
    "node.js",
    "nodejs",
    "express",
    "fastapi",
    "django",
    "flask",
    "rails",
    "spring",
    "laravel",
    "nestjs",
    "hono",
    "elysia",
    "graphql",
    "rest",
    "trpc",
    "grpc",
    "websocket",
    "prisma",
    "drizzle",
    "hasura",
    "postgresql",
    "mysql",
    "mongodb",
    "redis",
    "sqlite",
    "dynamodb",
    "cassandra",
    "elasticsearch",
    "supabase",
    "planetscale",
    "turso",
  ],
  other: [
    "frontend architecture",
    "developer tooling",
    "build systems",
    "webpack",
    "vite",
    "aws",
    "azure",
    "gcp",
    "google cloud",
    "cloudflare",
    "vercel",
    "heroku",
    "digitalocean",
    "docker",
    "kubernetes",
    "terraform",
    "ansible",
    "ci/cd",
    "github actions",
    "jenkins",
    "helm",
    "openai",
    "langchain",
    "pytorch",
    "tensorflow",
    "huggingface",
    "scikit-learn",
    "pandas",
    "numpy",
    "stripe",
    "twilio",
    "sendgrid",
  ],
};
